### ISSUE TITLE
Communication from the Android App to the Connect IQ Simulator does not work

### ISSUE THREAD

**Issue by pdeubel** [garmin/connectiq-android-sdk#2]
Hi, I have setup the project to have a working Connect IQ Simulator running with the watch app, and the Android App running on my phone which is connected with USB (I set the connection type to TETHERED, so that I can connect using ADB).

Currently working is that I can send data from the simulator to the Android app, i.e. the messages appear in the Android app. However the other way around does not work:
- When clicking "Tap here to open the Comm app on the device" in the Androidapp, a little popup at the bottom appears with "App Status: APP_IS_NOT_INSTALLED"
- When clicking any of the messages that shall be sent to the watch, the Android app crashes with the following stack trace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.garmin.android.apps.connectiq.sample.comm, PID: 16332
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:149)
        at com.garmin.android.connectiq.adb.AdbConnection.sendMessage(AdbConnection.java:196)
        at com.garmin.android.connectiq.ConnectIQAdbStrategy.sendMessageProtocol(ConnectIQAdbStrategy.java:127)
        at com.garmin.android.connectiq.ConnectIQ.sendMessage(ConnectIQ.java:941)
        at com.garmin.android.connectiq.ConnectIQ.sendMessage(ConnectIQ.java:921)
        at com.garmin.android.apps.connectiq.sample.comm.activities.DeviceActivity.onItemClick(DeviceActivity.kt:213)
        at com.garmin.android.apps.connectiq.sample.comm.activities.DeviceActivity.access$onItemClick(DeviceActivity.kt:35)
        at com.garmin.android.apps.connectiq.sample.comm.activities.DeviceActivity$buildMessageList$adapter$1.invoke(DeviceActivity.kt:203)
        at com.garmin.android.apps.connectiq.sample.comm.activities.DeviceActivity$buildMessageList$adapter$1.invoke(DeviceActivity.kt:203)
        at com.garmin.android.apps.connectiq.sample.comm.adapter.MessageViewHolder.bindTo$lambda-0(MessagesAdapter.kt:48)
        at com.garmin.android.apps.connectiq.sample.comm.adapter.MessageViewHolder.$r8$lambda$tM5NpG9NLj3wTw7LM00P2aTNOpg(Unknown Source:0)
        at com.garmin.android.apps.connectiq.sample.comm.adapter.MessageViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Do you have any idea why this is and how I can fix it?

Phone: Android 9, Garmin Connect is installed

**Comment by pdeubel** [comment]
For users that stumble across this: I found out, that the error is caused when sending messages from the main/UI thread. I made a PR with a fix, where messages are sent using a coroutine: #3

**Comment by pdeubel** [comment]
Hey sorry no idea where to get that constant, I did not modify it and for testing out smth I think it is not needed.

**Comment by veerviren** [comment]
@pdeubel can we please help me out I am also facing an similar issue 
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.garmin.android.apps.connectiq.sample.comm, PID: 16332
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:149)
        at com.garmin.android.connectiq.adb.AdbConnection.sendMessage(AdbConnection.java:196)
        at com.garmin.android.connectiq.ConnectIQAdbStrategy.sendMessageProtocol(ConnectIQAdbStrategy.java:127)
        at com.garmin.android.connectiq.ConnectIQ.sendMessage(ConnectIQ.java:941)
        at com.garmin.android.connectiq.ConnectIQ.sendMessage(ConnectIQ.java:921)
        at com.garmin.android.apps.connectiq.sample.comm.activities.DeviceActivity.onItemClick(DeviceActivity.kt:213)
        at com.garmin.android.apps.connectiq.sample.comm.activities.DeviceActivity.access$onItemClick(DeviceActivity.kt:35)
        at com.garmin.android.apps.connectiq.sample.comm.activities.DeviceActivity$buildMessageList$adapter$1.invoke(DeviceActivity.kt:203)
        at com.garmin.android.apps.connectiq.sample.comm.activities.DeviceActivity$buildMessageList$adapter$1.invoke(DeviceActivity.kt:203)
        at com.garmin.android.apps.connectiq.sample.comm.adapter.MessageViewHolder.bindTo$lambda-0(MessagesAdapter.kt:48)
        at com.garmin.android.apps.connectiq.sample.comm.adapter.MessageViewHolder.$r8$lambda$tM5NpG9NLj3wTw7LM00P2aTNOpg(Unknown Source:0)
        at com.garmin.android.apps.connectiq.sample.comm.adapter.MessageViewHolder$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by pdeubel** [comment]
@veerviren Hey sorry I am not up to date with that issue but your stacktrace looks a lot like mine, so you might check out my pull request that I referenced earlier in this thread. Maybe the code will help you, good luck!
